### ISSUE TITLE
Unable to run the demo evaluate_camvid.py

### ISSUE THREAD

**Issue by ice-pice** [fvisin/reseg#1]
Hi,
I am trying to run the demo evaluate_camvid.py code and I am fairly new to Theano and Lasagne. I get the following error (copying the whole log to explain after what steps the error is popping):

> Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled, cuDNN 4007)
> 5|True|RGB|None|True|None| |True|(360, 480)|False|False|False|conv3_3|()|()|GlorotUniform , Constant 0.0|rectify|[100, 100]|([1, 1], [1, 1])|(True, True)|GRULayer| |Constant 0.0|0|Gate Gate Gate Constant 0.0|grad|[50, 50]|[(2, 2), (2, 2)]|[(2, 2), (2, 2)]|GlorotUniform, Constant 0.0|rectify|None|None|False|False| |False| |adadelta|None|None,None,None,None|0.0|0.0|500|5000|100|0| | | | | ||
> Loading data ...
> Processing Camvid SegNet train dataset...
> Loading images...
> Loading masks...
> Processing Camvid SegNet valid dataset...
> Loading images...
> Loading masks...
> Processing Camvid SegNet test dataset...
> Loading images...
> Loading masks...
> load_data Done!
> Tot images:701 Train:367 Valid:101 Test:233
> num of classes: 193
> Building model ...
> Input shape: (None, 720, 960, 3)
> Vgg: After vgg: (None, 256, 180, 240)
> ReNet: After 2 rnns 1x1@100 and 2 rnns 1x1@100: (None, 200, 180, 240)
> ReNet: After 2 rnns 1x1@100 and 2 rnns 1x1@100: (None, 200, 180, 240)
> Transposed conv: 2x2 (str 2x2) @ 50:(None, 50, 360, 480)
> Transposed conv: 2x2 (str 2x2) @ 50:(None, 50, 720, 960)
> Starting training...
> Epoch 0/5000 Up 0 Cost 0.000000, DD 0.000000, UD 0.000000 0                                                                                                                                                                                  Traceback (most recent call last):
>   File "evaluate_camvid.py", line 241, in <module>
>     'reload': False
>   File "evaluate_camvid.py", line 110, in main
>     reload_=params['reload']
>   File "/home/exx/diggy/reseg/reseg.py", line 870, in train
>     class_balance_w)
>   File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0.dev1-py2.7.egg/theano/compile/function_module.py", line 875, in __call__
>     storage_map=getattr(self.fn, 'storage_map', None))
>   File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0.dev1-py2.7.egg/theano/gof/link.py", line 325, in raise_with_op
>     reraise(exc_type, exc_value, exc_trace)
>   File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0.dev1-py2.7.egg/theano/compile/function_module.py", line 862, in __call__
>     self.fn() if output_subset is None else\
> ValueError: dimension mismatch in x,y_idx arguments
> Apply node that caused the error: GpuCrossentropySoftmaxArgmax1HotWithBias(GpuReshape{2}.0, GpuElemwise{second,no_inplace}.0, GpuFromHost.0)
> Toposort index: 820
> Inputs types: [CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, vector), CudaNdarrayType(float32, vector)]
> Inputs shapes: [(3456000, 193), (193,), (10368000,)]
> Inputs strides: [(193, 1), (1,), (1,)]
> Inputs values: ['not shown', 'not shown', 'not shown']
> Outputs clients: [[GpuElemwise{mul,no_inplace}(GpuCrossentropySoftmaxArgmax1HotWithBias.0, GpuFromHost.0)], [GpuCrossentropySoftmax1HotWithBiasDx(GpuElemwise{Mul}[(0, 0)].0, GpuCrossentropySoftmaxArgmax1HotWithBias.1, GpuFromHost.0)], []]

I tried running using different installations of Theano and Lasagne wondering if that was the issue but to no use. My directory structure :
![image](https://cloud.githubusercontent.com/assets/4324025/16486460/77307660-3ee2-11e6-838c-8dc1eba37aec.png)

If anyone else has faced this problem, kindly help!!
Thanks!

**Comment by fvisin** [comment]
Hi,

you should resize the images to 480X360 resolution. I realized it was not specified in the README, so I  just updated it. Please let me know if that solves your issue.

**Comment by ice-pice** [comment]
Hi,

Thanks for your reply!
I have resized the images in all the data folders to 480X360, so now the log displays:

> Building model ...
> Input shape: (None, 360, 480, 3)
> Vgg: After vgg: (None, 256, 90, 120)

But this follows the same error as I have written above:

>   File "/usr/local/lib/python2.7/dist-packages/Theano-0.9.0.dev1-py2.7.egg/theano/compile/function_module.py", line 862, in __call__
>     self.fn() if output_subset is None else\
> ValueError: dimension mismatch in x,y_idx arguments

I also want to specify that I have changed "reseg.py: Line 824" to :
>    metrics_wid = VariableText( 'Cost %(cost)f, DD %(DD)f, UD %(UD)f %(shape)s',
>         {'cost': 0, 'DD': 0, 'UD': 0, 'shape': 0})

as it was giving me this error:

> Error while formatting 'Cost %(cost)f, DD %(DD)f, UD %(UD)f %(shape)s'
> {'DD': None, 'UD': None, 'cost': None, 'shape': None}
> TypeError: float argument required, not NoneType

What do you think I am missing?

**Comment by fvisin** [comment]
It looks like you have a shape problem at the end of the network, when the cross entropy is computed. 

I am traveling and I don't have my laptop with me so it will be difficult for me to try to reproduce your problem until I'm back, but in the meanwhile can you try to set `debug=True` at [this line](https://github.com/fvisin/reseg/blob/master/reseg.py#L33) and run the code again? This should give you more information on exactly where the code is falling and why. In this modality you can debug theano variables accessing their `tag.test_value` argument, e.g. the following will give you the shape of a variable `x`:
```python
# suppose x is a theano variable
x.tag.test_value.shape
```

Let me know what you find out and I'll try to help!

**Comment by MarcoCiccone** [comment]
Hi @ice-pice, can you also check your input data? the number of classes should be 11 plus the void, so 12, instead I see that you have 193. You can download the dataset from here [https://github.com/alexgkendall/SegNet-Tutorial/tree/master/CamVid](url) . 
Just let me know if you solved the issue or you need more support :)

**Comment by ice-pice** [comment]
Hi @MarcoCiccone, you are right on point.
My *annot files were not restricted to 12 values, instead they were colored which I downloaded from http://web4.cs.ucl.ac.uk/staff/g.brostow/MotionSegRecData/

I am able to run the training. Thank you @fvisin and @MarcoCiccone.
Cheers!

**Comment by fvisin** [comment]
That's great!

**Comment by brisker** [comment]
After running the evaluate_camvid.py, the command line looks like this:


```
jcc@jcc:~/PycharmProjects/reseg$ python evaluate_camvid.py
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled, cuDNN not available)
5|True|RGB|None|True|None| |True|(360, 480)|False|False|False|conv3_3|()|()|GlorotUniform , Constant 0.0|rectify|[100, 100]|([1, 1], [1, 1])|(True, True)|GRULayer| |Constant 0.0|0|Gate Gate Gate Constant 0.0|grad|[50, 50]|[(2, 2), (2, 2)]|[(2, 2), (2, 2)]|GlorotUniform, Constant 0.0|rectify|None|None|False|False| |False| |adadelta|None|None,None,None,None|0.0|0.0|500|5000|100|0| | | | | ||
Loading data ...
Processing Camvid SegNet train dataset...
Loading images...
Loading masks...
Processing Camvid SegNet valid dataset...
Loading images...
Loading masks...
Processing Camvid SegNet test dataset...
Loading images...
Loading masks...
load_data Done!
Tot images:701 Train:367 Valid:101 Test:233
# of classes: 12
Building model ...
Input shape: (None, 360, 480, 3)
Vgg: After vgg: (None, 256, 90, 120)
ReNet: After 2 rnns 1x1@100 and 2 rnns 1x1@100: (None, 200, 90, 120)
ReNet: After 2 rnns 1x1@100 and 2 rnns 1x1@100: (None, 200, 90, 120)
Transposed conv: 2x2 (str 2x2) @ 50:(None, 50, 180, 240)
Transposed conv: 2x2 (str 2x2) @ 50:(None, 50, 360, 480)
```

But why the code just stop here?!! No "starting training" after 10 minites! Why? Any help? 
@fvisin 
@marcociccone

**Comment by brisker** [comment]
error when running python evaluate_camvid.py:


```
jcc@jcc:~/PycharmProjects/reseg$ python evaluate_camvid.py
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled, cuDNN not available)
5|True|RGB|None|True|None| |True|(360, 480)|False|False|False|conv3_3|()|()|GlorotUniform , Constant 0.0|rectify|[100, 100]|([1, 1], [1, 1])|(True, True)|GRULayer| |Constant 0.0|0|Gate Gate Gate Constant 0.0|grad|[50, 50]|[(2, 2), (2, 2)]|[(2, 2), (2, 2)]|GlorotUniform, Constant 0.0|rectify|None|None|False|False| |False| |adadelta|None|None,None,None,None|0.0|0.0|500|5000|100|0| | | | | ||
Loading data ...
Processing Camvid SegNet train dataset...
Loading images...
Loading masks...
Processing Camvid SegNet valid dataset...
Loading images...
Loading masks...
Processing Camvid SegNet test dataset...
Loading images...
Loading masks...
load_data Done!
Tot images:701 Train:367 Valid:101 Test:233
# of classes: 12
Building model ...
Input shape: (None, 360, 480, 3)
Vgg: After vgg: (None, 256, 90, 120)
ReNet: After 2 rnns 1x1@100 and 2 rnns 1x1@100: (None, 200, 90, 120)
ReNet: After 2 rnns 1x1@100 and 2 rnns 1x1@100: (None, 200, 90, 120)
Transposed conv: 2x2 (str 2x2) @ 50:(None, 50, 180, 240)
Transposed conv: 2x2 (str 2x2) @ 50:(None, 50, 360, 480)
Starting training...
Error while formatting 'Cost %(cost)f, DD %(DD)f, UD %(UD)f %(shape)s'
{'DD': None, 'UD': None, 'cost': None, 'shape': None}
Traceback (most recent call last):
  File "evaluate_camvid.py", line 241, in <module>
    'reload': False
  File "evaluate_camvid.py", line 110, in main
    reload_=params['reload']
  File "/home/jcc/PycharmProjects/reseg/reseg.py", line 834, in train
    redirect_stdout=True).start()
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/progressbar/bar.py", line 606, in start
    self.update(self.min_value, force=True)
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/progressbar/bar.py", line 562, in update
    StdRedirectMixin.update(self, value=value)
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/progressbar/bar.py", line 150, in update
    DefaultFdMixin.update(self, value=value)
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/progressbar/bar.py", line 54, in update
    line = converters.to_unicode('\r' + self._format_line())
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/progressbar/bar.py", line 493, in _format_line
    widgets = ''.join(self._to_unicode(self._format_widgets()))
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/progressbar/bar.py", line 468, in _format_widgets
    widget_output = converters.to_unicode(widget(self, data))
  File "/home/jcc/PycharmProjects/reseg/utils.py", line 319, in __call__
    self.format)
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/progressbar/widgets.py", line 73, in __call__
    return (format or self.format) % data
TypeError: float argument required, not NoneType
```
Anyone help?
@fvisin 
@marcociccone
