### ISSUE TITLE
cannot import name TransposedConv2DLayer

### ISSUE THREAD

**Issue by saikrishna-1996** [fvisin/reseg#3]
when I run "python evaluate_camvid.py",
I am getting the following error message:
"
ERROR (theano.sandbox.cuda): nvcc compiler not found on $PATH. Check your nvcc installation and try again.
/home/saikrishna/.local/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
Traceback (most recent call last):
  File "evaluate_camvid.py", line 1, in <module>
    from reseg import train
  File "/home/saikrishna/reseg-master/reseg.py", line 22, in <module>
    from layers import CropLayer, ReSegLayer
  File "/home/saikrishna/reseg-master/layers.py", line 6, in <module>
    from lasagne.layers.conv import TransposedConv2DLayer
ImportError: cannot import name TransposedConv2DLayer

"

please help me resolve this issue
thank you!
Sai Krishna

**Comment by fvisin** [comment]
> ERROR (theano.sandbox.cuda): nvcc compiler not found on $PATH. Check your nvcc installation and try again.

It looks like you did not follow all the installation steps for Theano. Make sure you have properly installed Theano and that you pass the Theano tests (refer to the Theano website for info).

> from lasagne.layers.conv import TransposedConv2DLayer
ImportError: cannot import name TransposedConv2DLayer

It looks like you did not install Lasagne properly (maybe you did not run setup.py or add it to the PYTHONPATH?). Please make sure you follow all the installation steps reported on the website of Lasagne.

I am sorry I cannot be more helpful, but please understand that the code is provided "as is". I can provide limited support on it, but I cannot give support on the installation of the frameworks it depends on. :)

**Comment by fvisin** [comment]
I am closing the issue as is not related to ReSeg.
