### ISSUE TITLE
my own dataset?

### ISSUE THREAD

**Issue by SteveIb** [fvisin/reseg#6]
Hi,
is it possible to run your code on my own dataset?
Regards.

**Comment by fvisin** [comment]
Of course, but you will need to modify the code a bit.

The easiest thing will be to create your own dataset mimicking camvid.py. You will just need to implement the `properties` function and the `load_data` one: https://github.com/fvisin/reseg/blob/8040d190fcdb6d191faf9e33abe671a9c2fa2dad/camvid.py#L274

These are the set of arguments that will be passed to the `load_data` function (note that you can ignore some of them if you so wish):
https://github.com/fvisin/reseg/blob/8040d190fcdb6d191faf9e33abe671a9c2fa2dad/reseg.py#L615-L622

The last step should be to import your dataset and add it to the dict here: https://github.com/fvisin/reseg/blob/8040d190fcdb6d191faf9e33abe671a9c2fa2dad/reseg.py#L36

I cannot provide more support than this, but you should have all the information you need.
Cheers!

**Comment by SteveIb** [comment]
Thanks..
I will try run in the coming days. 
Regards.
