### ISSUE TITLE
VGG16.pkl

### ISSUE THREAD

**Issue by Asber777** [fvisin/reseg#7]
Download the VGG weights for Lasagne from: https://s3.amazonaws.com/lasagne/recipes/pretrained/imagenet/vgg16.pkl
but the page show that
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>49776127F6B192E1</RequestId>
<HostId>
bgKuGx2Gw25o0nTqDgDNexCouhJukt9xWb26YTyji7hHG60FaBIR6RBJBiypCPekwXs2hJrZuH0=
</HostId>
</Error>
and I couldn't find any vgg16.pkl on the Internet
where can I find it now?

**Comment by fvisin** [comment]
Thank you for your interest in our work. Unfortunately Theano has been discontinued some time ago, and this code is 4 years old. I am not sure where and if it is still possible to find the pretrained weights for vgg. 

if you want to build on this code, I would recommend to reimplement it in PyTorch or JAX.
